### ISSUE TITLE
CN links missing

### ISSUE THREAD

**Issue by Zokhoi** [resure/interwiki#14]
CN links are missing in the interwiki.
![Screenshot_20210718-014657_Brave.png](https://user-images.githubusercontent.com/20432565/126045638-19ebf476-f293-4d3b-9b65-1d1cf8356e79.png)

Last time when I saw CN links working was around 3pm of Jul 17, UTC+8.

**Comment by resure** [comment]
Thank you for reporting this. It looks like administrators of CN wiki have disabled API access to the site.

```
Error during pages list fetching (wiki: "scp-wiki-cn") Error: XML-RPC fault: Access to this site through the API is forbidden (configure in "Manage Site > API")
```

Interwiki uses Wikidot API to fetch list of the wiki pages.

**Comment by Zokhoi** [comment]
The CN master administrator has just re-enabled the API access. Are there any more things to do besides that?

**Comment by Zokhoi** [comment]
The CN link is back so I guess the problem is solved?
